#StorageSign default config.yml
no-permisson: You don't have permission

manual-import: true
manual-export: true
auto-import: true
auto-export: true
autocollect: true
hardrecipe: false

divide-limit: 34560
no-bud: false